Prepare workspace (#3)
* fix(): remove e2e test from old folder

* feat(infra): add manual deploy to vercel

* feat(infra): save artifact from vercel CLI

* feat(infra): add windows and macos targets for e2e

* feat(husky): add rules for pre-commit

* fix(gh-action): invalid literal syntax


Co-authored-by: Cristian Enguídanos Nebot <53697395+cenguidanos@users.noreply.github.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,24 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+# Check first if we are commiting to protected
+BRANCH="$(git branch --show-current)"
+
+if [ "$BRANCH" == "main" ]; then
+   echo "You can't commit to protected main"
+   exit 1
+fi
+
+if [ "$BRANCH" == "staging" ]; then
+   echo "You can't commit to protected staging"
+   exit 1
+fi
+
+if [ "$BRANCH" == "development" ]; then
+   echo "You can't commit to protected development"
+   exit 1
+fi
+
 # If we are in pipeline context, disable commands
 if [ "$GITHUB_CI" != true ]; then
    # Lint github/workflows yaml files
