Prepare workspace (main) (#5)
* feat(git): add main as proteted branch for husky pre-push

* feat(sonarcloud): add target development to sonarcloud branch

* feat(e2e): chang files for e2e testing

* fix(e2e): change testDir folder

* improve (#1)

* feat(refactor): simplify workspace

* fix(): remove e2e test from old folder

* feat(infra): add manual deploy to vercel

* feat(infra): save artifact from vercel CLI

* feat(infra): add windows and macos targets for e2e

* feat(husky): add rules for pre-commit

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(gh-action): invalid literal syntax

* fix(actions): remove unnecesary npm build

* fix(actions): change pnpm script to pnpx for test

* fix(actions): e2e reports path

* fix(actions): no reports located

* fix(actions): change playwright ci behavior

* fix(actions): change playwright ci behavior

* fix(actions): change playwright ci behavior

Co-authored-by: Cristian Enguídanos Nebot <53697395+cenguidanos@users.noreply.github.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,32 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-if [ "$GITHUB_CI" != true ]; then
-   pnpm lint
-   pnpm format
-   git add .
-else
-   echo "Pass commit without actions..."
+# Check first if we are commiting to protected
+BRANCH="$(git branch --show-current)"
+
+if [ "$BRANCH" == "main" ]; then
+   echo "You can't commit to protected main"
+   exit 1
 fi
+
+if [ "$BRANCH" == "staging" ]; then
+   echo "You can't commit to protected staging"
+   exit 1
+fi
+
+if [ "$BRANCH" == "development" ]; then
+   echo "You can't commit to protected development"
+   exit 1
+fi
+
+# Lint github/workflows yaml files
+sh "$PWD"/.github/scripts/yaml-linter.sh
+
+# Lint Next.js app
+pnpm lint
+
+# Format workspace
+pnpm format
+
+# Add changes to commit
+git add .
diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,26 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-if [ "$GITHUB_CI" != true ]; then
-   pnpm test -- --coverage
-   pnpm e2e
-else
-   echo "Pass push without actions..."
+# Check first if we are pushing to protected
+BRANCH="$(git branch --show-current)"
+
+if [ "$BRANCH" == "main" ]; then
+   echo "You can't push to protected main"
+   exit 1
 fi
+
+if [ "$BRANCH" == "staging" ]; then
+   echo "You can't push to protected staging"
+   exit 1
+fi
+
+if [ "$BRANCH" == "development" ]; then
+   echo "You can't push to protected development"
+   exit 1
+fi
+
+# Run Jest tests with coverage
+pnpm test -- --coverage
+
+# Run Playwright local E2E tests
+pnpm e2e
