fix: yaml linter

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,14 +4,14 @@
 # Check first if we are commiting to protected
 BRANCH="$(git branch --show-current)"
 
-if [ "$BRANCH" == "main" ]; then
-   echo "ERROR: You can't commit to protected main"
-   exit 1
-fi
-
 if [ "$SKIP_CHECK" == "true" ]; then
    echo "CAUTION: Skipping pre-commit hook"
 else
+   if [ "$BRANCH" == "main" ]; then
+      echo "ERROR: You can't commit to protected main"
+      exit 1
+   fi
+
    # Lint github/workflows yaml files
    sh "$PWD"/.github/scripts/yaml-linter.sh
 
