feat(git): add main as proteted branch for husky pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,6 +1,13 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+BRANCH="$(git branch --show-current)"
+
+if [ "$BRANCH" == "main" ]; then
+   echo "You can't push to protected main"
+   exit 1
+fi
+
 if [ "$GITHUB_CI" != true ]; then
    pnpm test -- --coverage
    pnpm e2e
